version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      production:
        dependency-type: production
        update-types: ["minor", "patch"]
