name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ "1.21", "1.22" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
          check-latest: true
      - uses: robherley/go-test-action@v0.4.1
        with:
          omitUntestedPackages: true
